### ISSUE TITLE
testinvoke list arguments limited to 16 elements

### ISSUE THREAD

**Issue by brianlenz** [CityOfZion/neo-python#213] opened 2018-02-07 06:51 UTC
There is a size limit of 16 elements for `testinvoke` list arguments:

```
Could not execute command: 'int' object has no attribute 'ToByteArray'
  File "~/.pyenv/versions/3.5.4/lib/python3.5/threading.py", line 882, in _bootstrap
    self._bootstrap_inner()
  File "~/.pyenv/versions/3.5.4/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "~/.pyenv/versions/3.5.4/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "~/.../neo-python2/venv/lib/python3.5/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "~/.../neo-python2/venv/lib/python3.5/site-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
  File "~/.../neo-python2/venv/lib/python3.5/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "~/.../neo-python2/venv/lib/python3.5/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "~/.../neo-python2/venv/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "~/.../neo-python2/venv/lib/python3.5/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "prompt.py", line 914, in run
    traceback.print_stack()
Traceback (most recent call last):
  File "prompt.py", line 889, in run
    self.test_invoke_contract(arguments)
  File "prompt.py", line 693, in test_invoke_contract
    tx, fee, results, num_ops = TestInvokeContract(self.Wallet, args)
  File "~/.../neo-python2/neo/Prompt/Commands/Invoke.py", line 177, in TestInvokeContract
    sb.push(listlength)
  File "~/.../neo-python2/neo/VM/ScriptBuilder.py", line 109, in push
    return self.push(binascii.hexlify(data.ToByteArray()))
AttributeError: 'int' object has no attribute 'ToByteArray'
```

All of the elements get pushed onto the stack in `TestInvokeContract`, but the call to `sb.push(listlength)` fails with a value > 16. Tracked this down to `ScriptBuilder`'s specialized handling of values between 1 and 16:

https://github.com/CityOfZion/neo-python/blob/master/neo/VM/ScriptBuilder.py#L106

If the value is greater than 16, it will fail since `int` doesn't have `ToByteArray`.

Is this limitation by design? I can't think of any way around the problem for now. This came up when trying to bulk add addresses to our SC for KYC. With over 5k addresses to whitelist, it would be nice to do more than 16 at a time, but we may not have any other option...

**Comment by ixje** [comment] 2018-02-07 07:37
An option might be to serialize the addresses up front and deserialize them on the SC. There are example routines in [neo-boa](https://github.com/CityOfZion/neo-boa/blob/master/boa/tests/src/SerializationTest.py) that use the _variable length type_ format as used in the NEO Network protocol ([see point 3 there](http://docs.neo.org/en-us/node/network-protocol.html#convention)).

**Comment by brianlenz** [comment] 2018-02-07 07:46
Thanks for the tip, @ixje! Will check it out 👍

**Comment by ixje** [comment] 2018-02-07 07:54
@brianlenz np, interested to hear if it works. Oh and regarding the limitation, I believe it's by design as `neo-vm` does the same [ref1](https://github.com/neo-project/neo-vm/blob/3fd0c9f09cbfdfffed86cbef845ad920f751a0fa/src/neo-vm/ScriptBuilder.cs#L52) [ref2](https://github.com/neo-project/neo-vm/blob/3fd0c9f09cbfdfffed86cbef845ad920f751a0fa/src/neo-vm/ExecutionEngine.cs#L77-L95). `neo-python`/`neo-boa` generally tries to closely follow the C# implementation.

**Comment by brianlenz** [comment] 2018-02-07 07:58
Hmm. @shargon was saying that neo-cli/neo-gui didn't have the same limitations, so I was going to try that out, as well. It definitely makes sense that they would be consistent, though!

We are quite close to deploying the SC, so I'm not sure we'll make the serialization changes in time. We may just have to bite the bullet and plow through the list in small chunks 😅

**Comment by shargon** [comment] 2018-02-07 11:53
I understand that should be equal as https://github.com/neo-project/neo-vm/blob/3fd0c9f09cbfdfffed86cbef845ad920f751a0fa/src/neo-vm/ScriptBuilder.cs#L65

But appear to be 
https://github.com/neo-project/neo-vm/blob/3fd0c9f09cbfdfffed86cbef845ad920f751a0fa/src/neo-vm/ScriptBuilder.cs#L52

In any case, you can build the arguments with

`PUSH *ADDRESS* and PACK`

I think that have a limit of 65535 bytes per script

**Comment by localhuman** [comment] 2018-02-07 23:03
Agreed with @shargon on sending in one large bytearray, you could send in a lot!  Though I don't think that with gas costs you could get more than 15 or 20 registrations in one invoke before you run out of free gas.

We will address the issue of the max list size of 16 though, as that doesn't seem nice!

**Comment by brianlenz** [comment] 2018-02-08 01:43
FWIW, I'm serializing 50 addresses and KYC whitelisting them in a single transaction while staying just under the 10 GAS limit :)

@localhuman do you think it's worth creating a neo-ico-template PR for the improvement I made? It's backwards compatible, so you can still pass in addresses, but it also supports passing in multiple addresses in a single byte array, which gets split into 20-byte chunks for each address. Changes for our SC here if you want to take a look and let me know if it's worthwhile:

https://github.com/NarrativeNetwork/tokensale-neo-smartcontract/compare/51782ab11ee3645d32fbee044254b0784bc7806c...master

I'm happy to create the PR if you think it'll add value to the template...

**Comment by ixje** [comment] 2018-08-01 19:51
Should we close this and label it as "won't fix" given that the C# ref implementation does the same (which we're still sort of following) (see https://github.com/CityOfZion/neo-python/issues/213#issuecomment-363685837)? or do you see good reasons to keep it open? @localhuman @metachris 

ps: i'm in issue cleanup mode that's why I'm asking 😆

**Closed** 2018-08-01 19:57 UTC
Labels: wontfix
