### ISSUE TITLE
sending 10 neo but tx information and block information shows vout value as 1

### ISSUE THREAD

**Issue by yanilkr** [CityOfZion/neo-python#349] opened 2018-03-22 00:38 UTC
### Current behavior
I am sending 10 neo to an address using np-prompt, the amount gets sent correctly and returns a transaction id. But when I view the transaction information using `np-prompt tx `, the vout information is wrong.  This is making my code to do wrong calculations.

- What is the problem?
Could be a python serialization issue. The same behavior is true for 100 or any amount that has trailing zeros. The amount shown strips off trailing zeros for amounts.

Lets say we have two Addresses "A" and "B". "A" has a1 neo and sends x1 amount of neo to "B". 

vout value in the transaction information should be something like this

>"vout": [
        {
            "n": 0,
            "asset": "0xc56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b",
            "value": "x1", // note here x1 is the amount sent 
            "address": "B"
        },
        {
            "n": 1,
            "asset": "0xc56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b",
            "value":  a1-x1,
            "address": "A"
        }
    ]

When I send x1 = 10 neo, the vout n=0 value shows 1 instead of 10

in the attached image, i send 20 it shows 2

![image](https://user-images.githubusercontent.com/195142/37744836-a12ba69c-2d2e-11e8-9fd2-174b7d1b0e67.png)

### Expected behavior

Make sure the vout value is correct when using np-prompt and rpc server

### How to reproduce
run np-prompt on privnet
open your wallet
> send neo ASdVCHRERMC4VPnjuAxaDswCWBVvv6pRUR 10
enter your password

you will get a transaction id.
in my case I got c3a5bbb9d03cf104bb059ce38888a47ace42a6d12e2774b3dad238b3c61e11af

> tx  c3a5bbb9d03cf104bb059ce38888a47ace42a6d12e2774b3dad238b3c61e11af

now inspect the vout array. n = 0, the value should be 10 but it shows 1.
 
### Your environment
latest neo-python.
debian linux jessie
neo-python v0.6.2
Python 3.6.4 :: Anaconda, Inc.

**Comment by localhuman** [comment] 2018-03-22 00:59
When looking at the transaction output, `n` refers to the index of the `vout` in the `vout` array.

The value that is in each `vout` is indicated by the `value` property.  In the case of ` c3a5bbb9d03cf104bb059ce38888a47ace42a6d12e2774b3dad238b3c61e11af`, you are sending the address ASdVCHRERMC4VPnjuAxaDswCWBVvv6pRUR 4977 Neo, it is taking 10 of them and then sending you back 4967.  You can view this transaction here:

https://neoscan-testnet.io/transaction/c3a5bbb9d03cf104bb059ce38888a47ace42a6d12e2774b3dad238b3c61e11af

**Comment by yanilkr** [comment] 2018-03-22 01:34
I understand what n is I am showing that “value” in vout array is wrong.

If you send any other amount without trailing zeros the “value” is correct .  Try sending 11 or 13 it works correctly try sending 10 or 20 or 100, the zeros at the end are stripped.

**Comment by localhuman** [comment] 2018-03-22 01:50
You need to understand the UTXO model.  Here is a good example:
https://www.ccn.com/bitcoin-transaction-really-works/

The neoscan link above also shows what is happening.

**Comment by yanilkr** [comment] 2018-03-22 02:05
Thanks for the link. I reviewed the link and I still think vout value is wrong. It’s such a major issue that you seem to refuse to believe this bug exists.

I think I know what I am talking about. I am founder of blockterms.com. Transaction processing is the core of what we do. I will be happy to be embarrassed by you. Please reproduce this issue on latest neo-python.

I also can verify that neoscan is showing the information correctly.

**Comment by localhuman** [comment] 2018-03-22 02:18
Sorry, you are correct.  It does seem that the values represented in the json representation of the tx are incorrect.  I think the issue is in this method:

https://github.com/CityOfZion/neo-python-core/blob/master/neocore/Fixed8.py#L138

**Comment by yanilkr** [comment] 2018-03-22 02:31
You already found the root cause so fast. Thanks for looking into it. Appreciate the quick response.

**Comment by localhuman** [comment] 2018-03-22 03:26
Fixed in latest version https://github.com/CityOfZion/neo-python/commit/74f719354d8f336b2727608ffca2eb1b37e00350 

Thanks again!

**Closed by localhuman** 2018-03-22 03:26 UTC
