### ISSUE TITLE
no connected peers

### ISSUE THREAD

**Issue by TimRi91** [CityOfZion/neo-python#541] opened 2018-08-09 14:39 UTC
### Current behavior

I send Smart-Contract-Invocation to my private-neo-network, which runs on a remote server on 4vCPUs.
The Rate of invocation should go up to 30requests per seconds.

After a while i get the error `no connected peers`

### Expected behavior
I was told the error occures because of the massiv workload of the network. 
The 4 consensus nodes respectively the docker container should be able to send this amount transactions per seconds.

### Your environment

- OS: Ubuntu 18.4
- neo-python version: 0.7.3
- Python version: 3.6.5

**Comment by ixje** [comment] 2018-08-09 16:53
>The 4 consensus nodes respectively the docker container should be able to send this amount transactions per seconds.

This is the wrong place to report that error. The consensus nodes are C# and the docker has nothing to do with `neo-python`. If those nodes become unresponsive due not being able to handle network load, then yes `neo-python` will show `no connected peers`. I also highly doubts that it's the consensus nodes not being able to handle the load as higher loads have been successful in the past.

Closing this for now. If you still think this is an issue with `neo-python` then please explain why you think so and give steps how to reproduce.

**Closed by ixje** 2018-08-09 16:53 UTC

**Comment by TimRi91** [comment] 2018-08-09 17:36
So the `no connected peers` is more a problem of the neo-private-network-docker-container? Then i open an issue in the neo-private-network-repo....

**Comment by ixje** [comment] 2018-08-09 17:58
`no connected peers` is just a `neo-python` status message that `neo-python` is not connected to any peers (= other nodes). This can be because there are no peers that are functional on the network, or because you have no network connection or anything. It's not per default a `neo-python` bug.

**Comment by TimRi91** [comment] 2018-08-09 17:59
But the neo-private-network causes that error, right?

**Comment by ixje** [comment] 2018-08-09 20:16
Could be, can also be your internet connection dropping seeing as you state have that private network running on a remote server, or it can be the server side disconnecting your. There are many reasons why this can happen and where ever you will report this it will require more investigation on your side because any maintainer cannot debug this for you without more data that only you can collect/provide.
