### ISSUE TITLE
Extreme use of computational resources after version v0.8.2

### ISSUE THREAD

**Issue by vncoelho** [CityOfZion/neo-python#917] opened 2019-03-20 16:32 UTC
### Current behavior
neo-py rest API server is currently using an incredible amount of computational resources.
Maybe there is some part of the code that was modified and is in loop `idle`, for example

A screenshot is depicted just for illustrating, but, in general, the use of a single CPU is almost from 90-99%.

![image](https://user-images.githubusercontent.com/17395762/54701455-d0241c00-4b13-11e9-9539-b8b0b0ce03d4.png)

### Your environment

- OS: (Linux distro) 

For tracking the issue I started a downgrading from version v0.7.10, which seems to be working normally.
I also tested v0.8.0,v0.8.1 and v0.8.2 (seems to be working normally).
I am can not be fully sure that these versions are safe, because tests were quick.

However, it is notorious that on v0.8.4 and also v0.8.3 the api_server.py is consuming much more resources.

**Comment by BeOleg** [comment] 2019-03-22 08:59
Same problem on a very strong bare metal dedicated box.
Maybe they are mining on our machines ;)

https://github.com/neo-project/neo/issues/648

**Comment by skinderis** [comment] 2019-03-22 09:17
I am facing the same issue, was discussing this on discord. I reduced the cpu usage by 50 % and it was syncing well, so it means it is using more resources than it needs

**Comment by ixje** [comment] 2019-03-22 10:34
This is the last thing I'm going to say on this topic. 

We're sorry to see release(s) that have this behaviour and they should have been captured before. It is currently one of the highest priority items and we have a build that moves away from the `Twisted` framework to `asyncio` that appears to resolve this and a bunch of other open issues related to performance. While it's near ready to be merged, I don't want to rush it and have regression. 

If you can't somehow limit the CPU usage like @skinderis did, then revert back to one of the older versions that don't have this issue as indicated by @vncoelho. Have a look at the Changelog to see what you might be missing out on. 

Again I personally want to resolve it a.s.a.p. All I can ask for is be patient for the moment.

**Comment by hal0x2328** [comment] 2019-03-22 12:01
I can replicate this on a fully synced node - I think this is because the callback loop between `start_block_persisting` and `persist_done`. If `Blockchain.Default().PersistBlocks()` has no work to do, it returns immediately, the `persist_done` callback is executed, and a new thread is spawned to call `PersistBlocks` again with no delay. So the process takes 100% cpu setting up and tearing down threads that don't do anything useful.

I tried added a `sleep` at line 106 in `persist_done`:
```
    if continue_persisting:
        sleep(0.1)
        start_block_persisting()
```
After adding this the CPU usage drops to 0.9%

**Closed** 2019-08-21 12:53 UTC
Labels: fixed in dev branch
