### ISSUE TITLE
contrib.smartcontract: Invoke smart contract methods

### ISSUE THREAD

**Issue by metachris** [CityOfZion/neo-python#104] opened 2017-11-27 15:16 UTC
Feature: Functionality for `contrib.smartcontract` to invoke SC methods.

I'm currently working on this. Using this issue for discussion, brainstorming and feedback.

As a reference: This was done for another project (imusify) like this: https://github.com/imusify/blockchain-middleware/blob/imusify2/imusify/imusmartcontract.py#L105

Thinking about a better way to integrate this -- in the above example it was a bit cumbersome with the wallet handling, waiting for the transactions to show up, and sometimes the wallet not showing correctly synced balances (this has been solved by the new neo-python updates).

**Comment by nettijoe96** [comment] 2018-03-17 06:04
- There is a local state that automatically updates after a transaction is sent to the network if the transaction will likely change the state of the blockchain. Bitcoin core does this with bitcoin-cli. In bitcoin core and everything forked from it (based on my tests) if you make a transaction, and send some bitcoin, the balance will change if you call ./bitcoin-cli getbalance (this is before the block is confirmed). Check out wallet/rpcwallet.cpp.
- I am trying to think of the benefits and costs of keeping state changes locally until they are confirmed in a block. It is a bit confusing to say that one's balance changed because someone cannot distinguish between a state change and a unconfirmed transaction. So maybe the solution is to have the updated balance but say something like "unconfirmed." What are your thoughts?
- The code that would have to be added is a way for the client to continually check the network and update one's personal wallet accordingly, which it already does.

**Comment by ixje** [comment] 2019-10-01 09:34
Closing due to focus on NEO3

**Closed by ixje** 2019-10-01 09:34 UTC
Labels: HACKIT
