### ISSUE TITLE
[Feature] Add RPC server

### ISSUE THREAD

**Issue by localhuman** [CityOfZion/neo-python#62] opened 2017-11-06 01:57 UTC
- Add RPC server to allow other clients to interface with `neo-python`

- Add tests for RPC server interface

**Comment by metachris** [comment] 2017-11-06 08:34
I would be interested in working on this.

What scope do you have in mind? JSON-RPC (& REST)? Which API calls? Perhaps we could use the wiki to draft up a quick API spec.

As web framework it would probably makes sense to just use Twisted, since it is already used as networking lib in neo-python. http://twistedmatrix.com/documents/current/web/howto/

**Comment by metachris** [comment] 2017-11-07 11:21
A few notes: I did some research and testing with the [Twisted web API](http://twistedmatrix.com/documents/current/web/). The documentation is not easy to follow, looks outdated in many areas, is not always reproducible, and is in general hard to implement.

Two popular web frameworks for using with Twisted are:

* https://github.com/twisted/klein ([ReadTheDocs](http://klein.readthedocs.io/en/latest)): popular and semi-active
* https://github.com/iancmcc/txrestapi: inactive since several years

Klein let's users define web routes/APIs like this:

    from klein import Klein
    app = Klein()

    @app.route('/')
    def pg_root(request):
        return 'I am the root page!'

    @app.route('/about')
    def pg_about(request):
        return 'I am a Klein application!'

    app.run("localhost", 8080)

From a developer usability point of view, I think Klein would be a good choice for implementing the JSON-RPC and REST API on top of Twisted.

**Comment by localhuman** [comment] 2017-11-07 13:07
Klein looks good! I also like this reference from their read me [Klein Bottle](https://en.wikipedia.org/wiki/Klein_bottle)

**Comment by metachris** [comment] 2017-12-02 13:55
See also #108 for related code.

**Comment by metachris** [comment] 2017-12-05 14:12
Question: What would be a few interesting API calls to start with?

**Comment by metachris** [comment] 2018-01-18 14:51
* Original RPC server implementation: https://github.com/neo-project/neo/blob/master/neo/Network/RPC/RpcServer.cs
* JSON RPC API reference https://github.com/neo-project/neo/wiki/API-Reference

**Comment by metachris** [comment] 2018-01-18 22:23
Work has started: https://github.com/CityOfZion/neo-python/tree/jsonrpc1

**Comment by metachris** [comment] 2018-01-23 10:41
Closing in favor of #189

**Closed by metachris** 2018-01-23 10:41 UTC
Labels: enhancement
